#!/usr/bin/env python

MODE_SLOW = 0b00000001  # Slow mode
MODE_SPEED_SET = 0b00000010  # Speed set
MODE_LASER_ON = 0b00000100  # Laser On
MODE_DIRECTION_LEFT = 0b00001000  # Going -X
MODE_DIRECTION_TOP = 0b00010000  # Going -Y
MODE_FINISHING = 0b00100000  # Finishing.
MODE_RESET = 0b01000000  # Reset

COMMAND_HOME = b'IPP'
COMMAND_UNLOCK_RAIL = b'IS2P'
COMMAND_LOCK_RAIL = b'IS2P'
COMMAND_S1P = b'S1P'
COMMAND_S1E = b'S1E'
COMMAND_RIGHT = b'B'
COMMAND_LEFT = b'T'
COMMAND_TOP = b'L'
COMMAND_BOTTOM = b'R'
COMMAND_ANGLE = b'M'
COMMAND_ON = b'D'
COMMAND_OFF = b'U'
COMMAND_NEXT = b'N'
COMMAND_S = b'S'
COMMAND_P = b'P'
COMMAND_E = b'E'
COMMAND_INTERRUPT = b'I'
COMMAND_SPEED = b'V'
COMMAND_CUT = b'C'
COMMAND_FINISH = b'F'
COMMAND_STEP = b'G'
COMMAND_RESET = b'@'
